Update cleaner script

diff --git a/bin/cleaner b/bin/cleaner
--- a/bin/cleaner
+++ b/bin/cleaner
@@ -1,82 +1,101 @@
 #!/bin/bash
 
 magenta='\e[1;35m'
+red='\e[1;31m'
 white='\e[0;37m'
 
-echo -e $magenta"\n Cleaning Package ... \n"$white
-sudo apt-get clean
+CMD="$1"
 
-echo -e $magenta"\n Autoleaning Package ... \n"$white
-sudo apt-get autoclean
+printusage() {
+    prog=$(basename "$0")
+    echo "Usage: $prog [-option]" >&2
+    echo "" >&2
+    echo "Options:" >&2
+    echo "    --help    Print this message" >&2
+    echo "    -s        Safe cleaner, except browser and image thumbnails" >&2
+    echo "    -a        Clean all unnecessary files" >&2
+}
 
-echo -e $magenta"\n Autoremoving Package ... \n"$white
-sudo apt-get autoremove
+safecleaner() {
+    echo -e $magenta"\n Cleaning Debian Packages ... \n"$white
+    sudo apt-get clean
 
-echo -e $magenta"\n Cleaning Gem ... \n"$white
-sudo gem cleanup
+    echo -e $magenta"\n Autocleaning Debian Packages ... \n"$white
+    sudo apt-get autoclean
 
-echo -e $magenta"\n Cleaning Composer Installer ... \n"$white
-sudo rm -fv ~/.composer/2016*
+    echo -e $magenta"\n Autoremoving Debian Packages ... \n"$white
+    sudo apt-get autoremove
 
-echo -e $magenta"\n Cleaning Junk in Home ... \n"$white
-rm -rfv ~/.cache/thumbnails/*
-rm -rfv ~/.thumbnails/*
-rm -rfv ~/.local/share/Trash/*
+    echo -e $magenta"\n Cleaning Gem ... \n"$white
+    sudo gem cleanup
 
-rm -rfv ~/.vim/backups/*
-rm -rfv ~/.vim/swaps/*
-rm -rfv ~/.vim/undo/*
+    echo -e $magenta"\n Cleaning Composer Installer ... \n"$white
+    sudo rm -fv ~/.composer/2016*
 
-echo -e $magenta"\n Cleaning Log System ... \n"$white
-sudo sh -c "echo > /var/log/dpkg.log"
-sudo sh -c "echo > /var/log/wtmp"
-sudo sh -c "echo > /var/log/lastlog"
-sudo sh -c "echo > /var/log/messages"
-sudo sh -c "echo > /var/log/secure"
-sudo sh -c "echo > /var/log/maillog"
-sudo sh -c "echo > /var/log/xferlog"
+    echo -e $magenta"\n Cleaning Shell History ... \n"$white
+    echo "" > ~/.bash_history && echo "" > ~/.zsh_history
 
-sudo rm -rfv /var/log/upstart/*1.gz
-sudo rm -rfv /var/log/apt/*.log
-sudo rm -rfv /var/log/mysql/*.log
-sudo rm -rfv /var/log/mysql/*.gz
-sudo rm -rfv /var/log/lightdm/*.log
-sudo rm -rfv /var/log/lightdm/*.old
+    echo -e $magenta"\n Cleaning Junk Files ... \n"$white
+    rm -rfv ~/.local/share/recently-used.xbel
+    rm -rfv ~/.xsession-errors*
+    rm -rfv ~/.local/share/Trash/*
 
-sudo rm -rfv /var/log/*.old &> /dev/null
-sudo rm -rfv /var/log/*.0 &> /dev/null
-sudo rm -rfv /var/log/*.1 &> /dev/null
-sudo rm -rfv /var/log/*.2 &> /dev/null
-sudo rm -rfv /var/log/*.3 &> /dev/null
-sudo rm -rfv /var/log/*.gz &> /dev/null
+    echo -e $magenta"\n Cleaning Vim ... \n"$white
+    rm -rfv ~/.vim/backups/*
+    rm -rfv ~/.vim/swaps/*
+    rm -rfv ~/.vim/undo/*
+    rm -rfv ~/.viminfo
 
-sudo rm -rfv /var/log/samba/*.old &> /dev/null
-sudo rm -rfv /var/log/samba/*.0 &> /dev/null
-sudo rm -rfv /var/log/samba/*.1 &> /dev/null
-sudo rm -rfv /var/log/samba/*.2 &> /dev/null
-sudo rm -rfv /var/log/samba/*.3 &> /dev/null
-sudo rm -rfv /var/log/samba/*.gz &> /dev/null
+    echo -e $magenta"\n Cleaning Log System ... \n"$white
+    sudo sh -c "echo > /var/log/dpkg.log"
+    sudo sh -c "echo > /var/log/wtmp"
+    sudo sh -c "echo > /var/log/lastlog"
+    sudo sh -c "echo > /var/log/messages"
+    sudo sh -c "echo > /var/log/secure"
+    sudo sh -c "echo > /var/log/maillog"
+    sudo sh -c "echo > /var/log/xferlog"
 
-sudo rm -rfv /var/log/apt/*.old &> /dev/null
-sudo rm -rfv /var/log/apt/*.0 &> /dev/null
-sudo rm -rfv /var/log/apt/*.1 &> /dev/null
-sudo rm -rfv /var/log/apt/*.2 &> /dev/null
-sudo rm -rfv /var/log/apt/*.3 &> /dev/null
-sudo rm -rfv /var/log/apt/*.gz &> /dev/null
+    sudo rm -rfv /var/log/apt/*.log
+    sudo rm -rfv /var/log/mysql/*.log
+    sudo rm -rfv /var/log/mysql/*.gz
+    sudo rm -rfv /var/log/nginx/*.log.1
+    sudo rm -rfv /var/log/lightdm/*.log
+    sudo rm -rfv /var/log/lightdm/*.old
+    sudo rm -rfv /var/log/lightdm/*.log.1.gz
 
-sudo rm -rfv /var/log/gdm/*.old &> /dev/null
-sudo rm -rfv /var/log/gdm/*.0 &> /dev/null
-sudo rm -rfv /var/log/gdm/*.1 &> /dev/null
-sudo rm -rfv /var/log/gdm/*.2 &> /dev/null
-sudo rm -rfv /var/log/gdm/*.3 &> /dev/null
-sudo rm -rfv /var/log/gdm/*.gz &> /dev/null
+    sudo rm -rfv /var/log/*.old &> /dev/null
+    sudo rm -rfv /var/log/*.0 &> /dev/null
+    sudo rm -rfv /var/log/*.1 &> /dev/null
+    sudo rm -rfv /var/log/*.2 &> /dev/null
+    sudo rm -rfv /var/log/*.3 &> /dev/null
+    sudo rm -rfv /var/log/*.gz &> /dev/null
 
-sudo rm -rfv /var/log/cups/*.old &> /dev/null
-sudo rm -rfv /var/log/cups/*.0 &> /dev/null
-sudo rm -rfv /var/log/cups/*.1 &> /dev/null
-sudo rm -rfv /var/log/cups/*.2 &> /dev/null
-sudo rm -rfv /var/log/cups/*.3 &> /dev/null
-sudo rm -rfv /var/log/cups/*.gz &> /dev/null
+    sudo rm -rfv /var/log/apt/*.old &> /dev/null
+    sudo rm -rfv /var/log/apt/*.0 &> /dev/null
+    sudo rm -rfv /var/log/apt/*.1 &> /dev/null
+    sudo rm -rfv /var/log/apt/*.2 &> /dev/null
+    sudo rm -rfv /var/log/apt/*.3 &> /dev/null
+    sudo rm -rfv /var/log/apt/*.gz &> /dev/null
+}
 
-echo -e $magenta"\n Cleaning History ... \n"$white
-echo "" > ~/.bash_history && echo "" > ~/.zsh_history
+if [[ -z "$1" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
+    printusage
+    exit 1
+fi
+
+case "$CMD" in
+    -s)
+        sudo echo -e $red"\n Executing a safe cleaner. \n"$white
+        safecleaner
+        ;;
+    -a)
+        sudo echo -e $red"\n Executing a whole cleaner. \n"$white
+        safecleaner
+        echo -e $magenta"\n Cleaning Thumbnails ... \n"$white
+        rm -rfv ~/.cache/thumbnails/*
+        rm -rfv ~/.thumbnails/*
+        ;;
+    *)
+        echo "Command not found"
+        ;;
+esac
